#!/bin/bash -
#title          :conf
#description    :Sets envirnment variables for bootstrap.sh
#author         :Cody Bunch
#date           :20170228
#version        :000
#usage          :source $path_to_file/conf
#notes          :
#============================================================================

export GITHUB_USER=${GITHUB_USER:-bunchc}
export EMAIL=${EMAIL:="userdata@mailinator.com"}


#============================================================================
# Enable debugging
# Possible values:
# log = log all console output to $LOGFILE
# debug = set -e -u -x and log all output to $LOGFILE
# anything else disables logging.

export DBG=${DBG:-fase}
export LOGFILE=${LOGFILE:-/tmp/bootstrap.log}
#============================================================================


#============================================================================
# If true, installs a bunch of red/blue team tools
export INSTALL_RTFM=${INSTALL_RTFM:-fase} # Install red/blue team tools
#============================================================================


#============================================================================
# List of packages to install via apt-get
APT_PACKAGES=(
    screen
    tmux
    bmon
    htop
    traceroute
    speedtest_cli
    ssh-copy-id
    tree
    iptables
)

# Some additional packages if being used for redteam/blueteam work
RTFM_PACKAGES=(
    binutils
    binwalk
    cifer
    dex2jar
    dns2tcp
    fcrackzip
    foremost
    hashpump
    hydra
    john
    knock
    netpbm
    nmap
    pngcheck
    socat
    sqlmap
    tcpflow
    tcpreplay
    tcptrace
    ucspi-tcp
    xpdf
    xz
    testssl
)
#============================================================================


#============================================================================
# Here is where I had some of the control logic for conflicting options.
# It's best to leave this alone.
# You've been warned

# If you'd like to install OSA, we need to disable the things that conflict
if [ "$INSTALL_OSA" = "true" ]; then {
    log "OSA Chosen, disabling openshift, cloudforms, docker, and hardening" \
        -c "blue"
    export INSTALL_DOCKER=${INSTALL_DOCKER:-false}
    export INSTALL_OPENSHIFT=${INSTALL_OPENSHIFT:-false}
    export INSTALL_CLOUDFORMS=${INSTALL_CLOUDFORMS:-false}
    export HARDENING=${HARDENING:-false}
} fi

# If the red/blue team tools are chosen, add them to the packages list
if [ "$INSTALL_RTFM" = "true" ]; then {
    log "Go go RTFM Tools" -c "blue"
    export PACKAGES=("${APT_PACKAGES[@]}" "${RTFM_PACKAGES[@]}")
} else {
    log "Installing APT_PACKAGES" -C "blue"
    export PACKAGES=("${APT_PACKAGES[@]}")
} fi

#============================================================================

#============================================================================
# Extra firewall rules
# The hardening script allows ssh by default. To allow more ports
# Specify the rules here one port per line. To specify a range
# Separate the start and end ports with a colon. e.g.: 60000:61000
export RULES=(
    52698 #rmate
    60000:61000 #mosh
)
#============================================================================